package com.revature.ecommerce.mappers;

import com.revature.ecommerce.dto.ProductDto;
import com.revature.ecommerce.entities.Product;
import org.mapstruct.*;

/*
 * This bean will be generated by map-struct.
 */
@Mapper(componentModel = MappingConstants.ComponentModel.SPRING)
public interface ProductMapper {
    /*
     * It maps the Dto and its corresponding entity for updating
     * It allows us to skip the fields with null value, so that we can partially update the fields with one method.
     */
    @BeanMapping(nullValuePropertyMappingStrategy = NullValuePropertyMappingStrategy.IGNORE)
    void updateProductFromDto(ProductDto productDto, @MappingTarget Product product);
}
