insert into sellers (first_name, last_name, email, password) values ('Jane', 'Doe', 'jane@email.com', '123')
--Products

insert into products (product_type, inventory, name, description, retail_price, discounted_price, threshold, seller_id) values ('book', 20, 'Test1', 'Lorem', 15.00, 10.00, 5, 1)
insert into products (product_type, inventory, name, description, retail_price, discounted_price, threshold, seller_id) values ('book', 20, 'Test2', 'Lorem', 15.00, 10.00, 5, 1)
insert into products (product_type, inventory, name, description, retail_price, discounted_price, threshold, seller_id) values ('book', 20, 'Test3', 'Lorem', 15.00, 10.00, 5, 1)
insert into products (product_type, inventory, name, description, retail_price, discounted_price, threshold, seller_id) values ('electronic', 20, 'Test4', 'Lorem', 15.00, 10.00, 5, 1)
insert into products (product_type, inventory, name, description, retail_price, discounted_price, threshold, seller_id) values ('electronic', 20, 'Test5', 'Lorem', 15.00, 10.00, 5, 1)
insert into products (product_type, inventory, name, description, retail_price, discounted_price, threshold, seller_id) values ('electronic', 20, 'Test6', 'Lorem', 15.00, 10.00, 5, 1)
insert into products (product_type, inventory, name, description, retail_price, discounted_price, threshold, seller_id) values ('book', 20, 'Test7', 'Lorem', 15.00, 10.00, 5, 1)
insert into products (product_type, inventory, name, description, retail_price, discounted_price, threshold, seller_id) values ('book', 20, 'Test8', 'Lorem', 15.00, 10.00, 5, 1)
insert into products (product_type, inventory, name, description, retail_price, discounted_price, threshold, seller_id) values ('book', 20, 'Test9', 'Lorem', 15.00, 10.00, 5, 1)
insert into products (product_type, inventory, name, description, retail_price, discounted_price, threshold, seller_id) values ('book', 20, 'Test10', 'Lorem', 15.00, 10.00, 5, 1)
insert into products (product_type, inventory, name, description, retail_price, discounted_price, threshold, seller_id) values ('book', 20, 'Test11', 'Lorem', 15.00, 10.00, 5, 1)
insert into products (product_type, inventory, name, description, retail_price, discounted_price, threshold, seller_id) values ('book', 20, 'Test12', 'Lorem', 15.00, 10.00, 5, 1)
insert into products (product_type, inventory, name, description, retail_price, discounted_price, threshold, seller_id) values ('book', 20, 'Test13', 'Lorem', 15.00, 10.00, 5, 1)
insert into products (product_type, inventory, name, description, retail_price, discounted_price, threshold, seller_id) values ('book', 20, 'Test14', 'Lorem', 15.00, 10.00, 5, 1)
insert into products (product_type, inventory, name, description, retail_price, discounted_price, threshold, seller_id) values ('book', 20, 'Test15', 'Lorem', 15.00, 10.00, 5, 1)