package com.revature.ecommerce.services;

import com.revature.ecommerce.dto.ProductDto;
import com.revature.ecommerce.entities.Product;
import org.mapstruct.*;

/*
 * This bean will be generated by map-struct.
 * It allows us to skip the fields with null value, so that we can partially update the fields with one method.
 */
@Mapper(componentModel = MappingConstants.ComponentModel.SPRING)
public interface ProductMapper {
    @BeanMapping(nullValuePropertyMappingStrategy = NullValuePropertyMappingStrategy.IGNORE)
    void updateProductFromDto(ProductDto productDto, @MappingTarget Product product);
}
